// Code generated by src/api/generate.py from servicelib/api/serviceapi.yaml. DO NOT EDIT.

use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(i32)]
pub enum UndefinedEnum {
    Undefined = 0,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(i32)]
pub enum ProgrammingLanguage {
    Undefined = 0,
    GoLang = 1,
    CppUserver = 2,
    Python = 3,
    Rust = 4,
    CppBoost = 5,
    TypeScript = 6,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(i32)]
pub enum JoinStorageType {
    Undefined = 0,
    HashMap = 1,
    RocksDB = 2,
    Aerospike = 3,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(i32)]
pub enum TransformationType {
    Undefined = 0,
    Input = 1,
    Map = 2,
    Filter = 3,
    Join = 4,
    MultiJoin = 5,
    Process = 6,
    FlatMap = 7,
    FlatMapIterable = 8,
    KeyBy = 9,
    Merge = 10,
    Split = 11,
    Case = 12,
    Sink = 13,
    CycleLink = 14,
    Error = 15,
    Delay = 16,
    When = 17,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(i32)]
pub enum JoinType {
    Undefined = 0,
    Inner = 1,
    Left = 2,
    Right = 3,
    Outer = 4,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum HTTPMethodType {
    #[serde(rename = "")]
    Undefined,
    #[serde(rename = "GET")]
    GET,
    #[serde(rename = "POST")]
    POST,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(i32)]
pub enum GrpcMethodType {
    Undefined = 0,
    NoStreaming = 1,
    ClientStreaming = 2,
    ServerStreaming = 4,
    BidirectionalStreaming = 5,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(i32)]
pub enum CallSemantics {
    Undefined = 0,
    Inherited = 1,
    FunctionCall = 2,
    TaskPool = 3,
    PriorityTaskPool = 4,
    ParallelCall = 5,
    DurableCall = 6,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(i32)]
pub enum DataConnectorType {
    Undefined = 0,
    HTTP = 1,
    GRPC = 2,
    Kafka = 3,
    Custom = 4,
    Cron = 5,
    Temporal = 6,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(i32)]
pub enum ProcessPattern {
    Undefined = 0,
    Execute = 1,
    Collect = 2,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum LogLevel {
    #[serde(rename = "")]
    Undefined,
    #[serde(rename = "CRITICAL")]
    CRITICAL,
    #[serde(rename = "FATAL")]
    FATAL,
    #[serde(rename = "ERROR")]
    ERROR,
    #[serde(rename = "WARNING")]
    WARNING,
    #[serde(rename = "INFO")]
    INFO,
    #[serde(rename = "DEBUG")]
    DEBUG,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum Environment {
    #[serde(rename = "")]
    Undefined,
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "debug")]
    Debug,
    #[serde(rename = "staging")]
    Staging,
    #[serde(rename = "production")]
    Production,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum KubernetesWorkloadType {
    #[serde(rename = "Deployment")]
    Deployment,
    #[serde(rename = "StatefulSet")]
    StatefulSet,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum DataConnectorImplementation {
    #[serde(rename = "")]
    Undefined,
    #[serde(rename = "net/http")]
    NetHTTP,
    #[serde(rename = "function")]
    Function,
    #[serde(rename = "IBM/Sarama")]
    IBMsarama,
    #[serde(rename = "google/grpc")]
    GoogleGRPC,
    #[serde(rename = "userver/http")]
    UserverHTTP,
    #[serde(rename = "userver/grpc")]
    UserverGRPC,
    #[serde(rename = "userver/kafka")]
    UserverKafka,
    #[serde(rename = "boost/beast-http")]
    BoostBeastHTTP,
    #[serde(rename = "asio/grpc")]
    AsioGRPC,
    #[serde(rename = "librdkafka")]
    Librdkafka,
    #[serde(rename = "aiohttp")]
    AioHTTP,
    #[serde(rename = "aiokafka")]
    AioKafka,
    #[serde(rename = "rust/axum")]
    RustAxum,
    #[serde(rename = "rust/tonic")]
    RustTonic,
    #[serde(rename = "rust/rdkafka")]
    RustRdkafka,
    #[serde(rename = "node/http")]
    NodeHTTP,
    #[serde(rename = "grpc/grpc-js")]
    GrpcJS,
    #[serde(rename = "confluent/kafka-javascript")]
    ConfluentKafkaJavaScript,
    #[serde(rename = "go/gocron")]
    GoGocron,
    #[serde(rename = "python/apscheduler")]
    PythonAPScheduler,
    #[serde(rename = "rust/croner")]
    RustCroner,
    #[serde(rename = "node/croner")]
    NodeCroner,
    #[serde(rename = "cpp/libcron")]
    CppLibcron,
    #[serde(rename = "temporal/go")]
    TemporalGo,
    #[serde(rename = "temporal/python")]
    TemporalPython,
    #[serde(rename = "temporal/typescript")]
    TemporalTypeScript,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum KafkaSecurityProtocol {
    #[serde(rename = "PLAINTEXT")]
    PLAINTEXT,
    #[serde(rename = "SASL_PLAINTEXT")]
    SASLPLAINTEXT,
    #[serde(rename = "SASL_SSL")]
    SASLSSL,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum KafkaSaslMechanism {
    #[serde(rename = "PLAIN")]
    PLAIN,
    #[serde(rename = "SCRAM-SHA-256")]
    SCRAMSHA256,
    #[serde(rename = "SCRAM-SHA-512")]
    SCRAMSHA512,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum ScheduleOverlapPolicy {
    #[serde(rename = "Allow")]
    Allow,
    #[serde(rename = "Skip")]
    Skip,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum ScheduleMissedRunPolicy {
    #[serde(rename = "Skip")]
    Skip,
    #[serde(rename = "FireOnce")]
    FireOnce,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize_repr, Deserialize_repr)]
#[repr(i32)]
pub enum TypeDefinitionFormat {
    Undefined = 0,
    Native = 1,
    Protobuf = 2,
    FlatBuffers = 3,
    CapNProto = 4,
    OpenAPI = 5,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "")]
    Undefined,
    #[serde(rename = "int")]
    Int,
    #[serde(rename = "uint")]
    Uint,
    #[serde(rename = "byte")]
    Byte,
    #[serde(rename = "char")]
    Char,
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "unicode char")]
    UnicodeChar,
    #[serde(rename = "string")]
    String,
    #[serde(rename = "unicode string")]
    UnicodeString,
    #[serde(rename = "float")]
    Float,
    #[serde(rename = "double")]
    Double,
    #[serde(rename = "int8")]
    Int8,
    #[serde(rename = "int16")]
    Int16,
    #[serde(rename = "int32")]
    Int32,
    #[serde(rename = "int64")]
    Int64,
    #[serde(rename = "uint8")]
    Uint8,
    #[serde(rename = "uint16")]
    Uint16,
    #[serde(rename = "uint32")]
    Uint32,
    #[serde(rename = "uint64")]
    Uint64,
    #[serde(rename = "any")]
    Any,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "schedule trigger")]
    ScheduleTrigger,
    #[serde(rename = "array")]
    Array,
    #[serde(rename = "map")]
    Map,
    #[serde(rename = "struct")]
    Struct,
    #[serde(rename = "custom")]
    Custom,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StreamApp {
    #[serde(rename = "settings")]
    pub settings: ProjectSettings,
    #[serde(rename = "streams")]
    pub streams: Vec<Stream>,
    #[serde(rename = "services")]
    pub services: Vec<Service>,
    #[serde(rename = "links")]
    pub links: Vec<Link>,
    #[serde(rename = "types")]
    pub types: Vec<Type>,
    #[serde(rename = "dataConnectors")]
    pub data_connectors: Vec<DataConnector>,
    #[serde(rename = "endpoints")]
    pub endpoints: Vec<Endpoint>,
    #[serde(rename = "pools")]
    pub pools: Vec<Pool>,
    #[serde(rename = "modules", skip_serializing_if = "Option::is_none")]
    pub modules: Option<Vec<Module>>,
    #[serde(rename = "undefinedEnum", skip_serializing_if = "Option::is_none")]
    pub undefined_enum: Option<UndefinedEnum>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProjectSettings {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "moduleVersion", skip_serializing_if = "Option::is_none")]
    pub module_version: Option<String>,
    #[serde(rename = "repoPath", skip_serializing_if = "Option::is_none")]
    pub repo_path: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Service {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "programmingLanguage")]
    pub programming_language: ProgrammingLanguage,
    #[serde(rename = "modulePath")]
    pub module_path: String,
    #[serde(rename = "golangVersion", skip_serializing_if = "Option::is_none")]
    pub golang_version: Option<String>,
    #[serde(rename = "defaultCallSemantics")]
    pub default_call_semantics: CallSemantics,
    #[serde(rename = "httpHost")]
    pub http_host: String,
    #[serde(rename = "httpPort")]
    pub http_port: i64,
    #[serde(rename = "statusHandler")]
    pub status_handler: String,
    #[serde(rename = "metricsHandler")]
    pub metrics_handler: String,
    #[serde(rename = "startupHandler")]
    pub startup_handler: String,
    #[serde(rename = "readinessHandler")]
    pub readiness_handler: String,
    #[serde(rename = "livenessHandler")]
    pub liveness_handler: String,
    #[serde(rename = "kubernetesWorkloadType")]
    pub kubernetes_workload_type: KubernetesWorkloadType,
    #[serde(rename = "grpcHost")]
    pub grpc_host: String,
    #[serde(rename = "grpcPort")]
    pub grpc_port: i64,
    #[serde(rename = "defaultGrpcTimeout")]
    pub default_grpc_timeout: i64,
    #[serde(rename = "color")]
    pub color: String,
    #[serde(rename = "shutdownTimeout")]
    pub shutdown_timeout: i64,
    #[serde(rename = "logLevel", skip_serializing_if = "Option::is_none")]
    pub log_level: Option<LogLevel>,
    #[serde(rename = "environment")]
    pub environment: Environment,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Pool {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "executorsCount")]
    pub executors_count: i64,
    #[serde(rename = "queueCapacity", skip_serializing_if = "Option::is_none")]
    pub queue_capacity: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Module {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "modulePath")]
    pub module_path: String,
    #[serde(rename = "golangVersion")]
    pub golang_version: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Stream {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "idSource")]
    pub id_source: i64,
    #[serde(rename = "idSources", skip_serializing_if = "Option::is_none")]
    pub id_sources: Option<Vec<i64>>,
    #[serde(rename = "type")]
    pub r#type: TransformationType,
    #[serde(rename = "valueType", skip_serializing_if = "Option::is_none")]
    pub value_type: Option<String>,
    #[serde(rename = "keyType", skip_serializing_if = "Option::is_none")]
    pub key_type: Option<String>,
    #[serde(rename = "idService")]
    pub id_service: i64,
    #[serde(rename = "idEndpoint", skip_serializing_if = "Option::is_none")]
    pub id_endpoint: Option<i64>,
    #[serde(rename = "joinType", skip_serializing_if = "Option::is_none")]
    pub join_type: Option<JoinType>,
    #[serde(rename = "joinStorage", skip_serializing_if = "Option::is_none")]
    pub join_storage: Option<JoinStorageType>,
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<ProcessPattern>,
    #[serde(rename = "xPos")]
    pub x_pos: f64,
    #[serde(rename = "yPos")]
    pub y_pos: f64,
    #[serde(rename = "functionName", skip_serializing_if = "Option::is_none")]
    pub function_name: Option<String>,
    #[serde(rename = "functionPackage", skip_serializing_if = "Option::is_none")]
    pub function_package: Option<String>,
    #[serde(rename = "publicFunction", skip_serializing_if = "Option::is_none")]
    pub public_function: Option<bool>,
    #[serde(
        rename = "functionDescription",
        skip_serializing_if = "Option::is_none"
    )]
    pub function_description: Option<String>,
    #[serde(
        rename = "functionInitializerGroup",
        skip_serializing_if = "Option::is_none"
    )]
    pub function_initializer_group: Option<String>,
    #[serde(rename = "functionModule", skip_serializing_if = "Option::is_none")]
    pub function_module: Option<String>,
    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i64>,
    #[serde(rename = "renewTTL", skip_serializing_if = "Option::is_none")]
    pub renew_ttl: Option<bool>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i64>,
    #[serde(rename = "pipeline", skip_serializing_if = "Option::is_none")]
    pub pipeline: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Link {
    #[serde(rename = "from")]
    pub from: i64,
    #[serde(rename = "to")]
    pub to: i64,
    #[serde(rename = "callSemantics")]
    pub call_semantics: CallSemantics,
    #[serde(rename = "async", skip_serializing_if = "Option::is_none")]
    pub r#async: Option<bool>,
    #[serde(rename = "poolName", skip_serializing_if = "Option::is_none")]
    pub pool_name: Option<String>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i64>,
    #[serde(rename = "idDataConnector", skip_serializing_if = "Option::is_none")]
    pub id_data_connector: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DataConnector {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: DataConnectorType,
    #[serde(rename = "implementation", skip_serializing_if = "Option::is_none")]
    pub implementation: Option<DataConnectorImplementation>,
    #[serde(rename = "goImplementation", skip_serializing_if = "Option::is_none")]
    pub go_implementation: Option<DataConnectorImplementation>,
    #[serde(
        rename = "cppUserverImplementation",
        skip_serializing_if = "Option::is_none"
    )]
    pub cpp_userver_implementation: Option<DataConnectorImplementation>,
    #[serde(
        rename = "cppBoostImplementation",
        skip_serializing_if = "Option::is_none"
    )]
    pub cpp_boost_implementation: Option<DataConnectorImplementation>,
    #[serde(
        rename = "pythonImplementation",
        skip_serializing_if = "Option::is_none"
    )]
    pub python_implementation: Option<DataConnectorImplementation>,
    #[serde(rename = "rustImplementation", skip_serializing_if = "Option::is_none")]
    pub rust_implementation: Option<DataConnectorImplementation>,
    #[serde(
        rename = "typeScriptImplementation",
        skip_serializing_if = "Option::is_none"
    )]
    pub type_script_implementation: Option<DataConnectorImplementation>,
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i64>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "connectionsCount", skip_serializing_if = "Option::is_none")]
    pub connections_count: Option<i64>,
    #[serde(rename = "brokers", skip_serializing_if = "Option::is_none")]
    pub brokers: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "dialTimeout", skip_serializing_if = "Option::is_none")]
    pub dial_timeout: Option<f64>,
    #[serde(rename = "usePartitioner", skip_serializing_if = "Option::is_none")]
    pub use_partitioner: Option<bool>,
    #[serde(rename = "async", skip_serializing_if = "Option::is_none")]
    pub r#async: Option<bool>,
    #[serde(rename = "securityProtocol", skip_serializing_if = "Option::is_none")]
    pub security_protocol: Option<KafkaSecurityProtocol>,
    #[serde(rename = "saslMechanism", skip_serializing_if = "Option::is_none")]
    pub sasl_mechanism: Option<KafkaSaslMechanism>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(
        rename = "useDedicatedListener",
        skip_serializing_if = "Option::is_none"
    )]
    pub use_dedicated_listener: Option<bool>,
    #[serde(rename = "module", skip_serializing_if = "Option::is_none")]
    pub module: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<String>,
    #[serde(
        rename = "maxConcurrentActivities",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_concurrent_activities: Option<i64>,
    #[serde(
        rename = "maxConcurrentWorkflows",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_concurrent_workflows: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Endpoint {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "idDataConnector")]
    pub id_data_connector: i64,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "httpMethodType", skip_serializing_if = "Option::is_none")]
    pub http_method_type: Option<HTTPMethodType>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "functionName", skip_serializing_if = "Option::is_none")]
    pub function_name: Option<String>,
    #[serde(rename = "functionPackage", skip_serializing_if = "Option::is_none")]
    pub function_package: Option<String>,
    #[serde(rename = "publicFunction", skip_serializing_if = "Option::is_none")]
    pub public_function: Option<bool>,
    #[serde(
        rename = "functionDescription",
        skip_serializing_if = "Option::is_none"
    )]
    pub function_description: Option<String>,
    #[serde(
        rename = "functionInitializerGroup",
        skip_serializing_if = "Option::is_none"
    )]
    pub function_initializer_group: Option<String>,
    #[serde(rename = "functionModule", skip_serializing_if = "Option::is_none")]
    pub function_module: Option<String>,
    #[serde(rename = "topic", skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(rename = "partitions", skip_serializing_if = "Option::is_none")]
    pub partitions: Option<i64>,
    #[serde(rename = "createTopic", skip_serializing_if = "Option::is_none")]
    pub create_topic: Option<bool>,
    #[serde(rename = "replicationFactor", skip_serializing_if = "Option::is_none")]
    pub replication_factor: Option<i64>,
    #[serde(rename = "consumerGroup", skip_serializing_if = "Option::is_none")]
    pub consumer_group: Option<String>,
    #[serde(rename = "grpcMethodType", skip_serializing_if = "Option::is_none")]
    pub grpc_method_type: Option<GrpcMethodType>,
    #[serde(rename = "methodName", skip_serializing_if = "Option::is_none")]
    pub method_name: Option<String>,
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<String>,
    #[serde(rename = "scheduleId", skip_serializing_if = "Option::is_none")]
    pub schedule_id: Option<String>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    #[serde(rename = "overlapPolicy", skip_serializing_if = "Option::is_none")]
    pub overlap_policy: Option<ScheduleOverlapPolicy>,
    #[serde(rename = "missedRunPolicy", skip_serializing_if = "Option::is_none")]
    pub missed_run_policy: Option<ScheduleMissedRunPolicy>,
    #[serde(rename = "taskQueue", skip_serializing_if = "Option::is_none")]
    pub task_queue: Option<String>,
    #[serde(
        rename = "workflowExecutionTimeout",
        skip_serializing_if = "Option::is_none"
    )]
    pub workflow_execution_timeout: Option<i64>,
    #[serde(
        rename = "activityStartToCloseTimeout",
        skip_serializing_if = "Option::is_none"
    )]
    pub activity_start_to_close_timeout: Option<i64>,
    #[serde(
        rename = "activityHeartbeatTimeout",
        skip_serializing_if = "Option::is_none"
    )]
    pub activity_heartbeat_timeout: Option<i64>,
    #[serde(rename = "maximumAttempts", skip_serializing_if = "Option::is_none")]
    pub maximum_attempts: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Type {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "type")]
    pub r#type: DataType,
    #[serde(rename = "valueType", skip_serializing_if = "Option::is_none")]
    pub value_type: Option<String>,
    #[serde(rename = "keyType", skip_serializing_if = "Option::is_none")]
    pub key_type: Option<String>,
    #[serde(rename = "definitionFormat", skip_serializing_if = "Option::is_none")]
    pub definition_format: Option<TypeDefinitionFormat>,
    #[serde(rename = "transferByValue", skip_serializing_if = "Option::is_none")]
    pub transfer_by_value: Option<bool>,
    #[serde(rename = "useAlias", skip_serializing_if = "Option::is_none")]
    pub use_alias: Option<bool>,
    #[serde(
        rename = "typeDefinitionLang1",
        skip_serializing_if = "Option::is_none"
    )]
    pub type_definition_lang1: Option<String>,
    #[serde(
        rename = "typeDefinitionLang2",
        skip_serializing_if = "Option::is_none"
    )]
    pub type_definition_lang2: Option<String>,
    #[serde(rename = "typeImportLang1", skip_serializing_if = "Option::is_none")]
    pub type_import_lang1: Option<String>,
    #[serde(rename = "typeImportLang2", skip_serializing_if = "Option::is_none")]
    pub type_import_lang2: Option<String>,
    #[serde(rename = "package", skip_serializing_if = "Option::is_none")]
    pub package: Option<String>,
    #[serde(rename = "publicType", skip_serializing_if = "Option::is_none")]
    pub public_type: Option<bool>,
    #[serde(rename = "module", skip_serializing_if = "Option::is_none")]
    pub module: Option<String>,
}
